version: '3.4'

services: 
  c_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq


volumes:
  rabbitmq:


